<?xml version="1.0" encoding="utf-8"?><Database Name="PharmacyDatabase" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-SM86SRG\SQLEXPRESS;Initial Catalog=PharmacyDatabase;Integrated Security=True;Trust Server Certificate=True" SettingsObjectName="Pharmacy_Management_System.Properties.Settings" SettingsPropertyName="PharmacyDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.category" Member="categories">
    <Type Name="category">
      <Column Name="catId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="catName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.customer" Member="customers">
    <Type Name="customer">
      <Column Name="cid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cname" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="phoneNo" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="customer_sale" Member="sales" ThisKey="cid" OtherKey="customerId" Type="sale" />
    </Type>
  </Table>
  <Table Name="dbo.LoginTable" Member="LoginTables">
    <Type Name="LoginTable">
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="userName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="userPassword" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="pid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="pname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ptype" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="sale_rate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="purchase_rate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="expiryDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="company" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="generic" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="batchNo" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="packSize" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="location" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="Product_purchase" Member="purchases" ThisKey="pid" OtherKey="productId" Type="purchase" />
      <Association Name="Product_sale" Member="sales" ThisKey="pid" OtherKey="productId" Type="sale" />
    </Type>
  </Table>
  <Table Name="dbo.purchase" Member="purchases">
    <Type Name="purchase">
      <Column Name="purId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="productId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="supplierId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="purchaseDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="productQuantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="total" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Product_purchase" Member="Product" ThisKey="productId" OtherKey="pid" Type="Product" IsForeignKey="true" />
      <Association Name="supplier_purchase" Member="supplier" ThisKey="supplierId" OtherKey="spId" Type="supplier" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.sale" Member="sales">
    <Type Name="sale">
      <Column Name="sid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="productId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="customerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="saleDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="productQuantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="total" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="customer_sale" Member="customer" ThisKey="customerId" OtherKey="cid" Type="customer" IsForeignKey="true" />
      <Association Name="Product_sale" Member="Product" ThisKey="productId" OtherKey="pid" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.supplier" Member="suppliers">
    <Type Name="supplier">
      <Column Name="spId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="spName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="spAddress" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="spPhone" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Association Name="supplier_purchase" Member="purchases" ThisKey="spId" OtherKey="supplierId" Type="purchase" />
    </Type>
  </Table>
</Database>